# Configuracion de produccion para uploads

server {
    listen 8080;
    root ./html;
    index index.html;

    # Raiz - solo lectura
    location / {
        root ./html;
        allow_methods GET HEAD;
        autoindex on;
    }

    # Upload - limite 10MB
    location /upload {
        root ./html;
        allow_methods GET POST DELETE;
        client_max_body_size 10M;
        autoindex on;
    }
}
