server {
    listen 8082;
    root ./html;
    index index.html;

    location / {
        root ./html;
        allow_methods GET POST DELETE HEAD;
        autoindex on;
    }

    location /upload {
        root ./html;
        allow_methods POST GET DELETE;
        client_max_body_size 1024M;
    }

    location /api {
        root ./html;
        allow_methods GET POST;
    }

    location /static {
        root ./html;
        allow_methods GET;
    }
}
