name: C++ Format, Lint and Compile Check

on:
  push:
    paths:
      - 'src/**'
      - 'test/**'
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'

jobs:
  clang-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install make and clang tools
      run: |
        sudo apt-get update
        sudo apt-get install -y make clang clang-format clang-tidy

    - name: Verify everything is formatted properly
      run: make format

    - name: Verify 
      run: make tidy

    - name: Verify everything compiles
      run: make
